# Generated by Django 5.0.6 on 2024-06-06 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Liga', '0005_equipo_usuario_jugador_usuario_liga_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='liga',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='equipo',
            unique_together={('nombre', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='jugador',
            unique_together={('nombre', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='liga',
            unique_together={('nombre', 'usuario')},
        ),
    ]
